name: Build & Push Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build base image
        run: |
          docker build \
            -f docker/base.Dockerfile \
            -t parzivalprime/my-node-base:latest .
          docker push parzivalprime/my-node-base:latest

      - name: Build deps image
        run: |
          docker build \
            -f docker/deps.Dockerfile \
            -t parzivalprime/my-node-deps:latest .
          docker push parzivalprime/my-node-deps:latest

      - name: Build api-gateway
        run: |
          docker build \
            -f apps/api-gateway/Dockerfile \
            -t parzivalprime/api-gateway:latest .
          docker push parzivalprime/api-gateway:latest

      - name: Build auth-service
        run: |
          docker build \
            -f apps/auth-service/Dockerfile \
            -t parzivalprime/auth-service:latest .
          docker push parzivalprime/auth-service:latest

      - name: Build product-service
        run: |
          docker build \
            -f apps/product-service/Dockerfile \
            -t parzivalprime/product-service:latest .
          docker push parzivalprime/product-service:latest

      - name: Build order-service
        run: |
          docker build \
            -f apps/order-service/Dockerfile \
            -t parzivalprime/order-service:latest .
          docker push parzivalprime/order-service:latest

      - name: Build kafka-service
        run: |
          docker build \
            -f apps/kafka-service/Dockerfile \
            -t parzivalprime/kafka-service:latest .
          docker push parzivalprime/kafka-service:latest
      
      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "/home/ubuntu/app/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app
            docker-compose down --rmi all -v --remove-orphans
            docker-compose pull
            docker-compose up -d