name: Build & Push Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build base image
        run: |
          docker build \
            -f docker/base.Dockerfile \
            -t parzivalprime/my-node-base:latest .
          docker push parzivalprime/my-node-base:latest

      - name: Build deps image
        run: |
          docker build \
            -f docker/deps.Dockerfile \
            -t parzivalprime/my-node-deps:latest .
          docker push parzivalprime/my-node-deps:latest

      - name: Build api-gateway
        run: |
          docker build \
            -f apps/api-gateway/Dockerfile \
            -t parzivalprime/api-gateway:latest .
          docker push parzivalprime/api-gateway:latest

      - name: Build auth-service
        run: |
          docker build \
            -f apps/auth-service/Dockerfile \
            -t parzivalprime/auth-service:latest .
          docker push parzivalprime/auth-service:latest

      - name: Build product-service
        run: |
          docker build \
            -f apps/product-service/Dockerfile \
            -t parzivalprime/product-service:latest .
          docker push parzivalprime/product-service:latest

      - name: Build order-service
        run: |
          docker build \
            -f apps/order-service/Dockerfile \
            -t parzivalprime/order-service:latest .
          docker push parzivalprime/order-service:latest
